# Generated by Django 2.2.7 on 2019-12-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=0, upload_to='catalog_images'),
            preserve_default=False,
        ),
    ]
